import { faker } from "@faker-js/faker";
import { generateProtocolForPacient } from "protocols-generator";

jest.mock("uuid", () => {
  return {
    v4: () => {
      return "string generated by mock";
    },
  };
});

describe("calculator tests", () => {
  it("Should generate a protocol for pacient", async () => {
    const firstName = faker.person.firstName();
    const lastName = faker.person.lastName();
    const priority = faker.datatype.boolean();

    const result = generateProtocolForPacient(firstName, lastName, priority);

    expect(result).toEqual({
      priority: priority,
      date: expect.any(Date),
      pacient: firstName + " " + lastName,
      protocol: expect.any(String),
    });
  });
});
